/** What one side of the before/after slider can show. */
export type PreviewSource =
  /** A static image. If it fails to load and fallbackHtml exists, that is rendered instead. */
  | { type: "image"; src: string; fallbackHtml?: string }
  /** A full HTML document, rendered in a sandboxed, scaled iframe. */
  | { type: "html"; html: string };

/** Successful response from POST /api/revamp */
export interface RevampApiResponse {
  ok: true;
  finalUrl: string;
  host: string;
  siteName: string;
  /** "ai" = generated by Claude, "template" = deterministic fallback */
  generator: "ai" | "template";
  /** The site paints itself with JavaScript, so a script-free snapshot would look empty */
  jsHeavy: boolean;
  title: string;
  description: string;
  beforeHtml: string;
  afterHtml: string;
}
