import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Footer from "../components/Footer";
import { BeforeAfterSlider } from "../components/BeforeAfterSlider";
import AiMetadata, { AiIntent } from "../components/AiMetadata";
import { getAttribution, getSessionIdForLead, trackAction } from "../lib/track";

type Viewport = "desktop" | "tablet" | "mobile";

type DemoSite = {
  id: string;
  name: string;
  industry: string;
  url: string;
  originalTitle: string;
  originalSubtitle: string;
  modernTitle: string;
  modernSubtitle: string;
  accent: string;
  beforeSrc: string;
  afterSrc: string;
};

const DEMO_SITES: DemoSite[] = [
  {
    id: "aurora-fitness",
    name: "Aurora Fitness",
    industry: "Fitness / gyms",
    url: "aurorafitness.example",
    originalTitle: "Cardio. Weights. Results.",
    originalSubtitle: "Open 7 days a week. First class always free.",
    modernTitle: "Build your experience.",
    modernSubtitle: "A confident, conversion-focused redesign built to turn visitors into booked trial classes.",
    accent: "#3fae6b",
    beforeSrc: "/images/revamps/aurora-fitness/before.png",
    afterSrc: "/images/revamps/aurora-fitness/after.png",
  },
  // Re-enable once /images/revamps/sushi/{before,after}.png are real,
  // non-empty files — see the image-generation prompt for these two.
  // {
  //   id: "sushi-restaurant",
  //   name: "Sakura Sushi",
  //   industry: "Hospitality / dining",
  //   url: "sakurasushi.example",
  //   originalTitle: "Welcome to Sushi Palace",
  //   originalSubtitle: "Open 7 days a week. Call for takeout.",
  //   modernTitle: "Savor the Art of Sushi.",
  //   modernSubtitle: "Experience Tokyo's finest flavors, crafted fresh daily.",
  //   accent: "#e63946",
  //   beforeSrc: "/images/revamps/sushi/before.png",
  //   afterSrc: "/images/revamps/sushi/after.png",
  // },
  // Re-enable once /images/revamps/plumber/{before,after}.png are real,
  // non-empty files.
  // {
  //   id: "plumber-agency",
  //   name: "FlowState Plumbing",
  //   industry: "B2B services",
  //   url: "flowstateplumbing.example",
  //   originalTitle: "Citywide Plumbing",
  //   originalSubtitle: "Residential, commercial, emergency service.",
  //   modernTitle: "Reliable Plumbing, Solved.",
  //   modernSubtitle: "A revolutionary professional plumbing solution company with expertise in reliable residential and commercial maintenance.",
  //   accent: "#3bb8c8",
  //   beforeSrc: "/images/revamps/plumber/before.png",
  //   afterSrc: "/images/revamps/plumber/after.png",
  // },
];

const ANALYSIS_STEPS = [
  "Reading the page structure...",
  "Mapping content and conversion paths...",
  "Applying PrismWave design tokens...",
  "Preparing a responsive preview...",
];

function Icon({ name }: { name: "globe" | "desktop" | "tablet" | "phone" | "layers" | "eye" | "arrow" | "close" }) {
  const paths: Record<string, string> = {
    globe: "M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm-9-9h18M12 3c2.2 2.4 3.2 5.4 3.2 9s-1 6.6-3.2 9c-2.2-2.4-3.2-5.4-3.2-9s1-6.6 3.2-9Z",
    desktop: "M3 4h18v12H3zM8 20h8M12 16v4",
    tablet: "M6 3h12v18H6zM10 18h4",
    phone: "M8 2h8v20H8zM11 18h2",
    layers: "m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5",
    eye: "M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6Zm10 3a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z",
    arrow: "M5 12h14m-6-6 6 6-6 6",
    close: "m6 6 12 12M18 6 6 18",
  };

  return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]} /></svg>;
}

async function fetchScreenshot(url: string): Promise<string> {
  const clean = url.replace(/^https?:\/\//, "");
  return `https://image.thum.io/get/width/1200/https://${clean}`;
}

function generatePreviewImage(siteName: string, accent: string): string {
  const html = `
    <div style="
      font-family: sans-serif;
      background: #0f0f0f;
      color: white;
      padding: 40px;
      border-radius: 20px;
      width: 100%;
      height: 100%;
      display: flex;
      flex-direction: column;
      gap: 20px;
    ">
      <div style="background:${accent};height:6px;width:60px;border-radius:3px;"></div>
      <h1 style="font-size:32px;margin:0;">Modern preview for ${siteName}</h1>
      <p style="opacity:0.7;line-height:1.5;">
        A clean, static redesign concept automatically generated by PrismWave Studio.
      </p>
      <div style="background:#1a1a1a;padding:20px;border-radius:12px;display:flex;flex-direction:column;gap:12px;">
        <div style="height:140px;background:#222;border-radius:8px;"></div>
        <div style="height:20px;background:#333;border-radius:4px;"></div>
        <div style="height:20px;background:#333;border-radius:4px;width:70%;"></div>
      </div>
    </div>
  `;

  return `data:text/html;charset=utf-8,${encodeURIComponent(html)}`;
}

export default function Revamp() {
  const [urlInput, setUrlInput] = useState("");
  const [activeSite, setActiveSite] = useState<DemoSite>(DEMO_SITES[0]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisStep, setAnalysisStep] = useState(0);
  const [viewport, setViewport] = useState<Viewport>("desktop");
  const [modalOpen, setModalOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lead, setLead] = useState({ name: "", email: "", business: "", note: "" });

  useEffect(() => {
    if (!isAnalyzing) return;
    const timer = window.setInterval(() => {
      setAnalysisStep((current) => {
        if (current >= ANALYSIS_STEPS.length - 1) {
          window.clearInterval(timer);
          setIsAnalyzing(false);
          return current;
        }
        return current + 1;
      });
    }, 500);
    return () => window.clearInterval(timer);
  }, [isAnalyzing]);

  const analyze = async (site: DemoSite) => {
    setIsAnalyzing(true);
    setAnalysisStep(0);

    // BEFORE screenshot
    const screenshot = await fetchScreenshot(site.url);

    // AFTER preview
    const preview = generatePreviewImage(site.name, site.accent);

    setActiveSite({
      ...site,
      beforeSrc: screenshot,
      afterSrc: preview,
    });

    setIsAnalyzing(false);

    trackAction("revamp_preview_generated", {
      metadata: { location: "revamp", site: site.name, industry: site.industry }
    });
  };


  const handleAnalyze = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const cleanUrl = urlInput.trim().replace(/^https?:\/\//i, "").split("/")[0];
    if (!cleanUrl) return;
    const preset = DEMO_SITES.find((site) => cleanUrl.toLowerCase().includes(site.url.split(".")[0]));
    
    const targetSite: DemoSite = preset ?? {
      id: `custom-${Date.now()}`,
      name: cleanUrl,
      url: cleanUrl,
      industry: "Your business",
      originalTitle: `${cleanUrl} — current experience`,
      originalSubtitle: "A real audit can reveal the highest-impact opportunities.",
      modernTitle: `A clearer digital front door for ${cleanUrl}.`,
      modernSubtitle: "A focused redesign concept based on your goals, audience, and next action.",
      accent: "#3fae6b",
      beforeSrc: DEMO_SITES[0].beforeSrc,
      afterSrc: DEMO_SITES[0].afterSrc,
    };
    
    analyze(targetSite);
  };

  const handleCloseModal = () => {
    setModalOpen(false);
    setSubmitted(false);
    setError(null);
    setLead({ name: "", email: "", business: "", note: "" });
  };

  const submitLead = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setSending(true);
    setError(null);
    try {
      const response = await fetch("/api/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          intent: "audit",
          name: lead.name,
          email: lead.email,
          business: lead.business || activeSite.name,
          siteUrl: activeSite.url,
          idea: "",
          message: lead.note || `I want to explore a full revamp for ${activeSite.name}.`,
          sessionId: getSessionIdForLead(),
          attribution: getAttribution(),
        }),
      });
      const data: { ok?: boolean; error?: string } = await response.json().catch(() => ({}));
      if (!response.ok || !data.ok) throw new Error(data.error ?? "The request could not be sent.");
      setSubmitted(true);
      trackAction("contact_submitted", { intent: "audit", metadata: { location: "revamp", site: activeSite.name } });
    } catch (submissionError) {
      setError(submissionError instanceof Error ? submissionError.message : "The request could not be sent.");
    } finally {
      setSending(false);
    }
  };

  const viewportClass = viewport === "mobile" ? "max-w-sm" : viewport === "tablet" ? "max-w-xl" : "max-w-3xl";

  return (
    <div className="grain min-h-screen overflow-x-clip bg-ink text-paper">
      <AiMetadata map={["Revamp engine", "URL input", "Before and after preview", "Lead capture"]} intent="Let a visitor preview a modern PrismWave redesign concept for an existing website and request a full implementation." tags={["website redesign", "interactive preview", "website audit", "conversion design"]} extract={{ title: "Instant Web Revamp Engine", audience: "Businesses with an existing website", primaryActions: "Generate a redesign preview or request implementation" }} />
      <header className="sticky top-0 z-40 border-b border-ink-line bg-ink/90 backdrop-blur-md">
        <div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
          <Link to="/" className="font-display text-base font-semibold tracking-tight text-paper sm:text-lg">PrismWave <span className="text-gradient">Studio</span></Link>
          <button type="button" onClick={() => setModalOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-amber px-4 py-2.5 font-display text-xs font-semibold text-ink transition-colors hover:bg-coral sm:text-sm">Request full implementation <Icon name="arrow" /></button>
        </div>
      </header>

      <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-16 lg:px-8">
        <section className="mx-auto max-w-3xl text-center">
          <p className="mb-4 inline-flex items-center gap-2 rounded-full border border-ink-line bg-ink-2/60 px-3 py-1.5 font-mono text-[11px] uppercase tracking-widest text-amber">Instant Web Revamp Engine</p>
          <h1 className="font-display text-4xl font-semibold leading-tight tracking-tight sm:text-5xl lg:text-6xl">See your website&apos;s <span className="text-gradient">next version.</span></h1>
          <AiIntent id="revamp-intent">Let visitors paste a website URL and preview a clearer, more modern conversion experience.</AiIntent>
          <p className="mt-5 text-base leading-relaxed text-ink-soft sm:text-lg">Paste an existing URL or try a sample. We&apos;ll create a visual redesign direction so you can see what a faster, clearer website could feel like before discussing the build.</p>
        </section>

        <section className="mx-auto mt-10 max-w-3xl">
          <form onSubmit={handleAnalyze} className="flex flex-col gap-3 sm:flex-row">
            <label className="relative flex min-h-12 flex-1 items-center">
              <span className="pointer-events-none absolute left-4 text-ink-soft"><Icon name="globe" /></span>
              <input type="text" value={urlInput} onChange={(event) => setUrlInput(event.target.value)} placeholder="yourbusiness.com" className="h-12 w-full rounded-xl border border-ink-line bg-ink-2/70 pl-11 pr-4 text-sm text-paper outline-none transition-colors placeholder:text-ink-soft/60 focus:border-amber sm:text-base" />
            </label>
            <button type="submit" disabled={isAnalyzing || !urlInput.trim()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-amber px-6 font-display text-sm font-semibold text-ink transition-colors hover:bg-coral disabled:cursor-not-allowed disabled:opacity-50">{isAnalyzing ? "Preparing preview..." : "Generate modern preview"}</button>
          </form>
          <div className="mt-4 flex flex-wrap items-center justify-center gap-2 text-xs text-ink-soft"><span className="mr-1">Try a sample:</span>{DEMO_SITES.map((site) => <button key={site.id} type="button" onClick={() => { setUrlInput(site.url); analyze(site); }} className={`min-h-11 rounded-lg border px-3 py-2 transition-colors ${activeSite.id === site.id ? "border-amber bg-amber/10 text-paper" : "border-ink-line hover:border-amber hover:text-paper"}`}>{site.name}</button>)}</div>
        </section>

        <section className="mt-12" aria-label="Interactive redesign workspace">
          <div className="mb-4 flex flex-col gap-4 rounded-xl border border-ink-line bg-ink-2/60 p-3 sm:flex-row sm:items-center sm:justify-between">
            <p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Drag the divider to compare</p>
            <div className="flex items-center gap-1 self-start rounded-lg border border-ink-line bg-ink p-1 sm:self-auto">
              {(["desktop", "tablet", "mobile"] as const).map((size) => <button key={size} type="button" onClick={() => setViewport(size)} aria-pressed={viewport === size} aria-label={`${size} viewport`} className={`flex min-h-11 min-w-11 items-center justify-center rounded-md transition-colors ${viewport === size ? "bg-ink-2 text-amber" : "text-ink-soft hover:text-paper"}`}><Icon name={size === "desktop" ? "desktop" : size === "tablet" ? "tablet" : "phone"} /></button>)}
            </div>
            <p className="hidden text-xs text-ink-soft lg:block"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-400" />Previewing {activeSite.name}</p>
          </div>

          <div className={`relative mx-auto overflow-hidden rounded-2xl border border-ink-line bg-ink-2 shadow-2xl transition-[max-width] duration-300 ${viewportClass}`}>
            {isAnalyzing && <div className="absolute inset-0 z-20 flex min-h-[480px] flex-col items-center justify-center bg-ink/95 p-6 text-center backdrop-blur-sm"><div className="h-1.5 w-56 overflow-hidden rounded-full bg-ink-line"><div className="h-full rounded-full bg-amber transition-[width] duration-300" style={{ width: `${((analysisStep + 1) / ANALYSIS_STEPS.length) * 100}%` }} /></div><h2 className="mt-5 font-display text-xl font-semibold">Building your preview</h2><p className="mt-2 font-mono text-xs text-amber">{ANALYSIS_STEPS[analysisStep]}</p></div>}
            <div className="min-h-[520px] p-4 sm:p-6">
              <BeforeAfterSlider
                beforeSrc={activeSite.beforeSrc}
                afterSrc={activeSite.afterSrc}
                beforeLabel={`BEFORE (${activeSite.industry})`}
                afterLabel="AFTER (PrismWave redesign)"
              />
              <div className="mt-6 grid gap-6 sm:grid-cols-2">
                <div>
                  <p className="font-mono text-[10px] uppercase tracking-widest text-[#a89f92]">Original direction</p>
                  <h2 className="mt-2 font-display text-xl font-semibold leading-tight">{activeSite.originalTitle}</h2>
                  <p className="mt-2 text-sm leading-relaxed text-ink-soft">{activeSite.originalSubtitle}</p>
                </div>
                <div>
                  <p className="font-mono text-[10px] uppercase tracking-widest text-amber">Modern direction</p>
                  <h2 className="mt-2 font-display text-xl font-semibold leading-tight">{activeSite.modernTitle}</h2>
                  <p className="mt-2 text-sm leading-relaxed text-ink-soft">{activeSite.modernSubtitle}</p>
                  <button type="button" onClick={() => setModalOpen(true)} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-full bg-amber px-5 py-3 font-display text-sm font-semibold text-ink transition-colors hover:bg-coral">Book the next step <Icon name="arrow" /></button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="mx-auto mt-12 grid max-w-5xl gap-4 sm:grid-cols-3"><div className="rounded-xl border border-ink-line bg-ink-2/60 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-amber">01 / Diagnose</p><p className="mt-3 text-sm leading-relaxed text-ink-soft">Use the existing site as a starting point, not a blank slate.</p></div><div className="rounded-xl border border-ink-line bg-ink-2/60 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-coral">02 / Clarify</p><p className="mt-3 text-sm leading-relaxed text-ink-soft">Make the value and next action obvious to the right visitor.</p></div><div className="rounded-xl border border-ink-line bg-ink-2/60 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-violet">03 / Build</p><p className="mt-3 text-sm leading-relaxed text-ink-soft">Turn the direction into a fixed-scope, owned implementation.</p></div></section>
      </main>

      {modalOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/85 p-4 backdrop-blur-sm"><div className="relative max-h-[calc(100dvh-2rem)] w-full max-w-md overflow-y-auto rounded-2xl border border-ink-line bg-ink-2 p-6 shadow-2xl sm:p-8"><button type="button" onClick={handleCloseModal} aria-label="Close request form" className="absolute right-4 top-4 flex h-11 w-11 items-center justify-center text-ink-soft hover:text-paper"><Icon name="close" /></button>{submitted ? <div className="py-12 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-amber text-amber">✓</div><h2 className="mt-5 font-display text-2xl font-semibold">Request received</h2><p className="mt-3 text-sm leading-relaxed text-ink-soft">I&apos;ll review your direction and reply within one business day.</p></div> : <><p className="font-mono text-[11px] uppercase tracking-widest text-amber">Full implementation</p><h2 className="mt-3 pr-8 font-display text-2xl font-semibold">Turn this direction into your real site.</h2><p className="mt-3 text-sm leading-relaxed text-ink-soft">Tell me where you are starting from. We&apos;ll confirm scope, price, and fit before any commitment.</p><form onSubmit={submitLead} className="mt-6 grid gap-4"><label className="grid gap-2 text-xs text-ink-soft">Name<input required value={lead.name} onChange={(event) => setLead({ ...lead, name: event.target.value })} className="min-h-11 rounded-lg border border-ink-line bg-ink px-3 text-sm text-paper outline-none focus:border-amber" /></label><label className="grid gap-2 text-xs text-ink-soft">Email<input required type="email" value={lead.email} onChange={(event) => setLead({ ...lead, email: event.target.value })} className="min-h-11 rounded-lg border border-ink-line bg-ink px-3 text-sm text-paper outline-none focus:border-amber" /></label><label className="grid gap-2 text-xs text-ink-soft">Business name<input required value={lead.business} onChange={(event) => setLead({ ...lead, business: event.target.value })} className="min-h-11 rounded-lg border border-ink-line bg-ink px-3 text-sm text-paper outline-none focus:border-amber" /></label><label className="grid gap-2 text-xs text-ink-soft">Notes<textarea rows={3} value={lead.note} onChange={(event) => setLead({ ...lead, note: event.target.value })} className="resize-y rounded-lg border border-ink-line bg-ink px-3 py-3 text-sm text-paper outline-none focus:border-amber" /></label>{error && <p className="font-mono text-xs text-coral">{error}</p>}<button type="submit" disabled={sending} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-amber px-5 py-3 font-display text-sm font-semibold text-ink disabled:opacity-60">{sending ? "Sending..." : "Request the full build"}<Icon name="arrow" /></button></form></>}</div></div>}
      <Footer />
    </div>
  );
}