// POST /api/revamp { url }
//
// Fetches the visitor's site server-side (browsers can't — CORS / frame
// blocking), then returns two self-contained HTML documents the Revamp page
// renders side by side in sandboxed iframes:
//   beforeHtml — the site's real page, scripts stripped, assets still loading from its host
//   afterHtml  — a redesigned homepage built from that site's own content:
//                generated by Claude when ANTHROPIC_API_KEY is set, otherwise (or if
//                the model fails / times out / the daily budget is spent) by the
//                deterministic template, so the visitor always gets a preview.

import { assertPublicHttpUrl } from "./_lib/ssrfGuard.js";
import { isClientRateLimited, isRateLimited } from "./_lib/rateLimit.js";
import { fetchPublicPage, readTextCapped } from "./_lib/safeFetch.js";
import { extractSiteContent } from "./_lib/siteExtract.js";
import { buildBeforeSnapshot, sanitizeGeneratedHtml } from "./_lib/previewHtml.js";
import { renderTemplate } from "./_lib/revampTemplate.js";
import { generateAfterHtml, isAiConfigured } from "./_lib/revampAi.js";

interface VercelLikeRequest {
  method?: string;
  body?: unknown;
  headers: Record<string, string | string[] | undefined>;
}

interface VercelLikeResponse {
  status(code: number): VercelLikeResponse;
  json(body: Record<string, unknown>): void;
}

const FETCH_TIMEOUT_MS = 9000;
const MAX_HTML_BYTES = 1_500_000;
const DAILY_AI_BUDGET = Number(process.env.REVAMP_AI_DAILY_LIMIT ?? 200);

function normalizeUrl(raw: string): string {
  const trimmed = raw.trim();
  return /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
}

export default async function handler(req: VercelLikeRequest, res: VercelLikeResponse): Promise<void> {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed." });
    return;
  }

  // Each call can cost real money (model tokens), so cap it per visitor...
  if (await isClientRateLimited(req.headers, { bucket: "revamp", limit: 6, windowSeconds: 600 })) {
    res.status(429).json({ error: "You've generated a few previews already — please try again in a few minutes." });
    return;
  }

  const body = req.body;
  const rawUrl =
    typeof body === "object" && body !== null && typeof (body as Record<string, unknown>).url === "string"
      ? ((body as Record<string, unknown>).url as string)
      : "";
  if (!rawUrl.trim() || rawUrl.length > 300) {
    res.status(400).json({ error: "Please enter a website address." });
    return;
  }

  const targetUrl = normalizeUrl(rawUrl);
  try {
    new URL(targetUrl);
    await assertPublicHttpUrl(targetUrl);
  } catch {
    res.status(400).json({ error: "That address can't be previewed. Check it and try again." });
    return;
  }

  // ---- 1. fetch the current site ------------------------------------------
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  let html: string;
  let finalUrl: string;
  try {
    const fetched = await fetchPublicPage(targetUrl, controller.signal);
    finalUrl = fetched.finalUrl;

    if (!fetched.response.ok) {
      res.status(502).json({ error: `That site responded with a ${fetched.response.status} error.` });
      return;
    }
    const contentType = fetched.response.headers.get("content-type") ?? "";
    if (contentType && !/html|xml/i.test(contentType)) {
      res.status(422).json({ error: "That address didn't return a web page." });
      return;
    }
    html = await readTextCapped(fetched.response, MAX_HTML_BYTES);
  } catch (err) {
    const aborted = err instanceof Error && err.name === "AbortError";
    console.error("Revamp fetch failed:", err);
    res.status(aborted ? 504 : 502).json({
      error: aborted
        ? "That site took too long to respond."
        : "Couldn't reach that site — check the address and try again.",
    });
    return;
  } finally {
    clearTimeout(timeout);
  }

  if (!/<html|<body|<head/i.test(html)) {
    res.status(422).json({ error: "That address didn't return a readable web page." });
    return;
  }

  // ---- 2. understand it ------------------------------------------------------
  const content = extractSiteContent(html, finalUrl);
  const beforeHtml = buildBeforeSnapshot(html, finalUrl);

  // ---- 3. redesign it --------------------------------------------------------
  let afterHtml = "";
  let generator: "ai" | "template" = "template";

  // ...and cap total AI spend per day. Over budget = template, not an error.
  const withinBudget = isAiConfigured() && !(await isRateLimited("global", { bucket: "revamp-ai-day", limit: DAILY_AI_BUDGET, windowSeconds: 86_400 }));

  if (withinBudget) {
    try {
      afterHtml = sanitizeGeneratedHtml(await generateAfterHtml(content));
      generator = "ai";
    } catch (err) {
      console.error("Revamp AI generation failed, using template:", err);
    }
  }

  if (!afterHtml) afterHtml = sanitizeGeneratedHtml(renderTemplate(content));

  res.status(200).json({
    ok: true,
    finalUrl,
    host: content.host,
    siteName: content.siteName,
    generator,
    // Tiny visible text = the site paints itself with JavaScript, so the
    // script-free snapshot will look empty; the client prefers a screenshot then.
    jsHeavy: content.textLength < 250,
    title: content.h1 || content.title,
    description: content.description,
    beforeHtml,
    afterHtml,
  });
}